[project]
name = "mangaready"
version = "0.1.0"
description = "Service for reading manga"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "fastapi>=0.115.12",
    "orjson>=3.10.16",
    "pydantic>=2.11.3",
    "pydantic-settings>=2.9.1",
]
